### ISSUE TITLE
Running Errors when installing through CocoaPods, Xcode 9.4.1

### ISSUE THREAD

**Issue by bamamoun** [wordpress-mobile/AztecEditor-iOS#1008]
When I install the framework through Cocoapods and run my project again, I get 136 Errors on the files dowloaded.
I am using the last version of Xcode.
Can you fix this ? 

Thank you!!

**Comment by CivelXu** [comment]
Use  develop branch
```pod 'WordPress-Aztec-iOS', :git => 'https://github.com/wordpress-mobile/WordPress-Aztec-iOS.git', :branch => 'develop'```

**Comment by diegoreymendez** [comment]
@bamamoun - I'd recommend to use at this time our latest beta.  We're getting close to releasing it as stable 1.0.
