### ISSUE TITLE
How to extract the html code of editor view

### ISSUE THREAD

**Issue by bamamoun** [wordpress-mobile/AztecEditor-iOS#1009]
Hello,
I would like to extract the html code of the text written,
If possible as a html file.
how can I Do that ?

Thank you!

**Comment by diegoreymendez** [comment]
Use [`Aztec.TextView`'s `getHTML()`](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Aztec/Classes/TextKit/TextView.swift#L696) method.
