### ISSUE TITLE
How to show the generated html in a UI view with the rich content (style, links, images...)

### ISSUE THREAD

**Issue by bamamoun** [wordpress-mobile/AztecEditor-iOS#1016]
Apart from the content created in the editor, I would like to display the content created without editing mode with its html code but still have the rich content with clickable links and display of images.

How can I do that using Aztec ?

Thank you !

**Comment by SergioEstevao** [comment]
Hello there you can just set the ```isEditable``` property of Aztec TextView to false.

This will allow you to see the generated richtext from the HTML set, but not allow edits.
