### ISSUE TITLE
Is this possible to insert custom html code programatically in between of html

### ISSUE THREAD

**Issue by vaibhavsingla1996** [wordpress-mobile/AztecEditor-iOS#1020]
### Expected behavior
Hi there I need to insert my custom html at a any point in editor at run time.

### Actual behavior
I am unable to find a function which can add any custom html at any point . I can only find a method to get html and set it again but it will add it at the end of code not in the middle or any point in editor. I am looking for a function just like 

> insertText()

which can add certain text at any point. I hope you understand my concern.

Thanks

**Comment by diegoreymendez** [comment]
Unfortunately there's no support right now to do this.  I'll turn this issue into a feature request.

**Comment by diegoreymendez** [comment]
Upcoming fix: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1026
