### ISSUE TITLE
Improve label on pasting actions in Edit Menu

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/AztecEditor-iOS#1028]
There are currently 2 ways to paste clipboard content into Aztec via an Edit Menu: `Paste` and `Paste and Match Style`. These options seem to be confusing to folks, especially the `Paste and Match Style` option.

### Proposal

Change `Paste and Match Style` menu item to instead say `Paste Without Formatting`. This label is more explicit.

* `Paste` should paste the content as is, and retain style if possible
* `Paste without formatting` should paste the content as plain-text, removing styling

Side note: I'm not sure if we should also retain links for the `paste without formatting` option. Thoughts @mattmiklic @elibud ?

### Steps to reproduce the behavior

1. Copy some content like a paragraph with some links from a mobile web browser
2. Start a new post or open an existing post
3. Tap somewhere in canvas to show Edit Menu
4. See menu items

**Comment by mattmiklic** [comment]
Good call with what's proposed here.

> I'm not sure if we should also retain links for the paste without formatting option. 

I discussed this with @diegoreymendez and I believe we're changing this so "Paste without formatting" should be completely plaintext, without preserving the links.

**Comment by iamthomasbishop** [comment]
Ok, let's roll with that then. I'll comment on the related Android issue that I just found ☝️☝️
