### ISSUE TITLE
Bug: textColor got smooshed

### ISSUE THREAD

**Issue by garsdle** [wordpress-mobile/AztecEditor-iOS#1040]
### Expected behavior
textView.textColor = myColor sets the default color

### Actual behavior
it does nothing

### Steps to reproduce the behavior
set textColor to something other than dark gray and setHtml 

##### Tested on [device], iOS [version], Aztec [version]
iPhoneX iOS 11 latest commit. [This is the commit that broke it](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1025/commits/e59b8d6d59e51262ea39d427ff175237eb5cbb22)

Not sure if there's another way to set the color? If so this is a question and not a bug :)

**Comment by benpackard** [comment]
This is still an issue, and with dark mode rumored for the next iOS release, might become more important.

It looks like `textColor` stopped being respected as part of a previous bug fix for issue https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1024, which is related to text formatting on paste. I am submitting a pull request to reinstate.

**Comment by benpackard** [comment]
Reinstating the removed code (adding the `textColor`, if set,  to `defaultAttributes` as `.foregroundColor`) did not work.

**Comment by SergioEstevao** [comment]
This is being fixed here: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1245
