### ISSUE TITLE
RegexProcessor regular expression range issue

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#1048]
### Expected behavior

The conversions between NSRange and Swift's range should be always using UTF16View's range(String.UTF16View.Index)

### Actual behavior
Now it's  using String's range(String.Index)

### Steps to reproduce the behavior

1. Ente Demo -> Video Shortcode Demo
2. Input any emoji before Shortcode
3. Switch to code mode and switch back

Here is a video I just recorded for showing the issue:
[ScreenRecording_09-05-2018 12-01-46.MP4.zip](https://github.com/wordpress-mobile/AztecEditor-iOS/files/2351356/ScreenRecording_09-05-2018.12-01-46.MP4.zip)

##### Tested on iPhone, iOS 11.4.1, Aztec 1.0.0-beta.25

**Comment by diegoreymendez** [comment]
Nice find.
