### ISSUE TITLE
I can't call a method without @objc when I use objective-c

### ISSUE THREAD

**Issue by JazzPC** [wordpress-mobile/AztecEditor-iOS#1055]
In objective-c project  when i use the TextView instance I want to call some method example the replaceWithImage because These methods don't have @objc
 

Can you add @objc to methods？thanks

 iOS [10.0], Aztec [1.0.0]

**Comment by SergioEstevao** [comment]
Aztec was planned to be used in Swift, we are not planning to support an interface for Objective C.

One way around this is to create a Swift class(es) in your project that wraps around Aztec class(es) and provide @obj methods to interact with the functionality you need.
