### ISSUE TITLE
Test pasting from common 3rd party Apps.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#1058]
### Description:

Considering that paste is apparently broken for [Google Docs](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1056) and [Word](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1057), we should definitely test other commonly used editors.

**Comment by jkmassel** [comment]
One other fairly common use-case to test: Apple Notes

Some examples of issues:
1363334-zen
1446382-zen

**Comment by diegoreymendez** [comment]
Closing as this issue is too broad to define a priority.  We can open more specific issues as bugs are reported.
