### ISSUE TITLE
After adding "NSAttributedStringKey", the text comes out of the HTML TAG

### ISSUE THREAD

**Issue by hubfactory** [wordpress-mobile/AztecEditor-iOS#1072]
I have Question.

I add NSAttributedStringKey.

```
public static let colorFormatKey = NSAttributedStringKey("Color.formatKey")
```

And at Formatter apply Function, I add 'resultingAttributes[colorFormatKey]'.

and, move to caret position, text is out of TAG.

Example:

First - 

<img width="268" alt="2018-10-18 17 51 24" src="https://user-images.githubusercontent.com/17402727/47150864-f9494200-d312-11e8-8b1c-70caefd97c6a.png">

HTML : 
```
<p>あかさたな<span style="color: #0000ff;">はまやらわ</span>あたなやま</p>
```
Second -

I moved caret position

<img width="263" alt="2018-10-18 17 51 47" src="https://user-images.githubusercontent.com/17402727/47150925-2f86c180-d313-11e8-828f-d8d900efaafa.png">

Third -

I type new text...

<img width="293" alt="2018-10-18 17 52 05" src="https://user-images.githubusercontent.com/17402727/47150979-5f35c980-d313-11e8-9b61-8153857fcef0.png">

HTML : 
```
<p>あかさたな<span style="color: #0000ff;">はま</span>あたま<span style="color: #0000ff;">やらわ</span>あたなやま</p>
```

I am sorry for the confusing explanation

I would be happy if you tell me what to do.

**Comment by diegoreymendez** [comment]
You probably need [something like this](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift#L8), but for the `color` CSS attribute.

CSS support is a bit limited at the moment, but there's a mechanism in place to make it work.  The class I linked above is the one that takes care of converting bold `NSAttributedString` styles, to either a tag or a matching CSS attribute.

[The matcher](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift#L10) is the class that takes care of outputting CSS whenever makes sense .

**Comment by diegoreymendez** [comment]
By the way, if you ever get around to implementing this, it would be a nice contribution to the project.

**Comment by diegoreymendez** [comment]
Closing for now, but let me know if there's more.
