### ISSUE TITLE
Insert Link Bug in Japanese text

### ISSUE THREAD

**Issue by hubfactory** [wordpress-mobile/AztecEditor-iOS#1075]
Hi.

## Bug Situation
insert text link in Japanese, example:  "あああ いいい".
HTML is 
```
<a href="test" target="" rel="noopener">あああ</a><a href="test" target="" rel="noopener"> </a><a href="test" target="" rel="noopener">いいい</a>
```

## Question
It is divided by space.
Is there a way to fix the code?

Best Regards.

**Comment by shengyang998** [comment]
Hi @hubfactory , did you solve the problem?
