### ISSUE TITLE
Nested blockquote style

### ISSUE THREAD

**Issue by sergstav** [wordpress-mobile/AztecEditor-iOS#1086]
Hello to all, thank for awesome library. I use it for displaying static html text, by using isEditable=false.
I try to display nested blockqutotes, with same style as parent one.
### Expected behavior
Expected behavior: nested blockquotes has the same style as parent one: at least left border line.

<blockquote><blockquote>многострочная цитатка<blockquote>теперь оч сложный вариант<br />сначала тут текст у нас<br />потом внизу цитата</blockquote><br /><div><br /></blockquote><br />вло<br /><br /></blockquote>

### Actual behavior
Nested quotes display as usual text, but with tab.
![screen shot 2018-11-18 at 5 31 34 pm](https://user-images.githubusercontent.com/3393265/48674730-25492480-eb58-11e8-81a4-92f62c7bd967.png)

### Steps to reproduce the behavior
Create nested blockquote text. For example:
<blockquote>hi test<blockquote>nested one</blockquote></blockquote>

##### Tested on [device], iOS [version], Aztec [version]
Tested on iOS Simulator iPhone XR
iOS 12.1
Aztec version 1.1

**Comment by MadeByDouglas** [comment]
I agree, this would be nice. im investigating a solution, will update here if I come up with anything.

**Comment by MadeByDouglas** [comment]
OK PR is open #1252
