### ISSUE TITLE
Parsing spans with colors

### ISSUE THREAD

**Issue by sergstav** [wordpress-mobile/AztecEditor-iOS#1087]
### Expected behavior
I saw some issues in this repo related to parse colors from the html, but now this functionality is broken
Expected behavior: span will be colored.
### Actual behavior
Colors in the html ignored
Actualy, example Project in the repo ignores colors.

### Steps to reproduce the behavior
Just use span with colors in the html.

##### Tested on [device], iOS [version], Aztec [version]
iOS Simulator, iOS 12.1, Aztec 1.1

**Comment by SergioEstevao** [comment]
This was fixed by this PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1215
