### ISSUE TITLE
Crash: Aztec String+RangeConversion crash

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/AztecEditor-iOS#1098]
Mirrored from: https://github.com/wordpress-mobile/WordPress-iOS/issues/10548

**Comment by diegoreymendez** [comment]
@jkmassel - Any chance the unit test can be narrowed a bit by trimming the content to the minimum necessary to make it crash?

Reason is: I want it to be clear what exactly is the issue, and it's a bit hard to tell with a large example content.
