### ISSUE TITLE
Hard returns removed inside <pre> tag when post edited in iOS App

### ISSUE THREAD

**Issue by damiannep** [wordpress-mobile/AztecEditor-iOS#1122]
### Expected behavior
When you edit a post in iOS that was created using the web editor, the whitespace inside of a pre tag added by pressing enter would remain.

### Actual behavior
White space in the form of hard returns inside a pre tag is removed.

### Steps to reproduce the behavior
1. Create a post at WordPress.com in the web browser. with a pre tag such as:

> <pre># puppet 
> --version4.10.12</pre>

2. Publish the post
3. Edit the post in the iOS app

##### Tested on [device], iOS [version], Aztec [version]
User reported in #9098555-hc. Will update with the details once I have them

**Comment by ccwalburn** [comment]
User returned with the following details in 1673721-zen:
iPhone se 
App 11.4.1 
iOS 12.1.2 (might have been 12.1.1 when I did it, the update was very recent)

**Comment by SergioEstevao** [comment]
Tested on the latest version of the app 14.3 and this no longer happens.
