### ISSUE TITLE
Conform to Community Standards

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/AztecEditor-iOS#1125]
To promote consistency across `WordPress-iOS` frameworks & to conform to [recommended community standards](https://github.com/wordpress-mobile/AztecEditor-iOS/community), we should update this repository to include all of the following:

- [X] Description
- [X] README
- [x] Code of conduct
- [X] Contributing
- [X] License
- [x] Issue templates
- [X] Pull request template

We should also modify the PR checks we have in place for consistency with `WordPress-iOS` (e.g., build checks, approval / merge requirements, etc.).

**Comment by diegoreymendez** [comment]
This can be closed.  If there's any specific change required let's track it through a new issue.
