### ISSUE TITLE
[Aztec iOS] Edit tagColor property of Aztec.EditorView

### ISSUE THREAD

**Issue by mePy2** [wordpress-mobile/AztecEditor-iOS#1130]
At the moment it’s possible to create a new `editorView: UITextView` view and set it up with `let storage = HTMLStorage(defaultFont: Constants.defaultContentFont)` and then `storage.tagColor = UIColor.red` since the `HTMLStorage` is an open class and `open var tagColor = Styles.defaultTagColor` too.
But it is not possible to modify the `tagColor` var inside the already set `Aztec.EditorView`.

Please, I need it to be black or another color. If you can, help me. I didn’t found any solution but to modify the framework, which is something I would like not to do.

**Comment by SergioEstevao** [comment]
At the moment the `HTMLStorage` property of `EditorView` is an public variable and the `tagColor` is also public so you should be able to change the color to your needs.
