### ISSUE TITLE
Shortcode support discussion.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#115]
We want to have shortcode parity with the existing WPiOS HTML editor.

This ticket is open for discussion, I'll create a new one once we can agree to a more precise specification.

[Here's the list of shortcodes](https://en.support.wordpress.com/shortcodes/) that WordPress.com supports.

**Comment by diegoreymendez** [comment]
Leaving without a milestone for the time being, and until higher priority items are delivered.

**Comment by diegoreymendez** [comment]
This feature will be v2.  No need to discuss it for now.

**Comment by SergioEstevao** [comment]
My proposal to implement this is to do the following:

 - Pre parse the HTML to replace shortcode in the HTML from this format ```[shortcode] Something [/shortcode]``` to ```< shortcode > </shortcode >``` then this will regular HTML elements that we can implement visualization
 - When saving the HTML we do the reverse, the things that are know shortcakes are reversed to the format ```[shortcode] Something [/shortcode]```

**Comment by SergioEstevao** [comment]
The implementation of shortcode is also a mandatory to implement things like video and captions, because they are implemented using shortcode in WordPress.

**Comment by diegoreymendez** [comment]
This discussion can be closed for now, as we have a default implementation already in.  Any other requests can be made through more specific GitHub issues.
