### ISSUE TITLE
There was a problem inserting an image

### ISSUE THREAD

**Issue by WeiRuJian** [wordpress-mobile/AztecEditor-iOS#1171]
Running the demo of the example, I made an error when inserting the picture. I did not encounter this problem before. I wonder if it is because I am using Xcode10.2

**Comment by diegoreymendez** [comment]
Can you provide more info about the problem and how we can reproduce it?

**Comment by WeiRuJian** [comment]
![image](https://user-images.githubusercontent.com/15668221/56005741-8be7fe00-5d04-11e9-9e76-11caea389064.png)
The program stopped at this location when I tried to insert an image. I ran the AztecExample example to insert an image in the EmptyDemo. This was also the problem, probably because I was using Xcode10.2 and had no problem before updating Xcode10.2.
