### ISSUE TITLE
Pasting doesnt invoke shouldChangeTextIn

### ISSUE THREAD

**Issue by Narek1994** [wordpress-mobile/AztecEditor-iOS#1189]
Hi, thanks for this lib

I have a text length limitation, and implemented shouldChangeTextIn to check it, but pasting text doesnt invoke this method, is this correct behaviour?

**Comment by diegoreymendez** [comment]
@Narek1994 - Unfortunately there's not enough information in this issue to be able to assist.  `shouldChangeTextIn` isn't a method known by Aztec so in principle, whether that method is invoked or not is entirely up to your code.

For general programming questions I suggest http://stackoverflow.com.

If there's anything more specific you'd like to ask please feel free to add more information to this issue.

I'm closing for now as there's nothing else we can do to assist at this time.

**Comment by Narek1994** [comment]
Thanks for reply
`func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) ` is a textView delegate method which invokes when text should be changed or not, when I am just writing it is invoking, but when I am copy pasting the text, it doesnt invoke, but it should be
https://stackoverflow.com/questions/12454857/how-to-know-when-text-is-pasted-into-uitextview
I tried it even in your example, same result, I guess copying and pasting text in textView made in different way than it is in default textView, if its possible could you please try that in your example as well. Thanks.

**Comment by diegoreymendez** [comment]
Reopening since there are now more details to evaluate.

**Comment by Narek1994** [comment]
hi, is there any news?
Thanks.
