### ISSUE TITLE
Custom FormatBar

### ISSUE THREAD

**Issue by XavierLost** [wordpress-mobile/AztecEditor-iOS#1241]
**Is your feature request related to a problem? Please describe.**

Custom FormatBar, Change subview height, Horizontal, vertical offset

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MadeByDouglas** [comment]
can you edit this to remove the boiler plate and just say what you want done? How do you think the custom font bar should be?

**Comment by SergioEstevao** [comment]
For the record the format is totally configurable, we provide one example in the demo app but you can switch to anything you want by changing it to your own custom view:

```
textView.inputAccessoryView = formatBar
```

Of course then you will need to implement the hooks between the actions in you toolbar and the appropriate commands to the TextView.
