### ISSUE TITLE
font sizes gets scaled down (about 25% it seems?)

### ISSUE THREAD

**Issue by MadeByDouglas** [wordpress-mobile/AztecEditor-iOS#1250]
**Describe the bug**
When setting default font to size 14, the output is actually 10.78

**To Reproduce**
in `EditorDemoController` there is the property  `static let defaultContentFont   = UIFont.systemFont(ofSize: 14)` however output font size is actually 10.78, it looks noticeably smaller than it should. This is confirmed when pasted into another text editor or app.

**Expected behavior**
Setting font size to 14 should product output of size 14

**Screenshot**
<img width="1920" alt="Screen Shot 2019-12-06 at 1 06 38 PM" src="https://user-images.githubusercontent.com/10858053/70356537-77bfb680-1829-11ea-8156-10dad4374227.png">

**Comment by MadeByDouglas** [comment]
Also, not sure if this is related, but you are not able to copy and paste text from Aztec into the native Mac mail app. Maybe its unsupported font size? p tag? I'm not sure, it works fine pasting into the the TextEdit app

**Comment by SergioEstevao** [comment]
@MadeByDouglas I think the reason of this discrepancy is that we are scaling the font to the "default" body style in iOS on the init method of TextView: 

```
self.defaultFont = UIFontMetrics.default.scaledFont(for: defaultFont)
``` 
This was done in order to support dynamic font size, but it shouldn't be part of the library, the users of the library should set the font and opt-in for dynamic sizing if they want.

**Comment by MadeByDouglas** [comment]
hmm, ok I see. Well it must be more than that, I tried replacing that instance and every other instance of scaledFont with a fixed setting and it didnt seem to change anything. Let me know what you find.

<img width="1314" alt="Screen Shot 2019-12-09 at 8 08 18 PM" src="https://user-images.githubusercontent.com/10858053/70494328-c1c1ca00-1abf-11ea-97bd-b929fd2baf52.png">

**Comment by MadeByDouglas** [comment]
Update: this may be an issue with simulator. That would be fine, but then more importantly it seems to be an issue with Mac Catalyst which also has the issue with Aztec. I was working with a completely different text editor and with catalyst had the scaling issue, when its a native AppKit app, not a problem.

**Comment by MadeByDouglas** [comment]
OK I can confirm this is not an aztec issue but rather with Mac catalyst.
https://twitter.com/stroughtonsmith/status/1135891985510912001

possible solution https://gist.github.com/stefanceriu/3c21452b7d481ceae41c0ca5f0f5c15d
