### ISSUE TITLE
Feature request: Generate links automatically?

### ISSUE THREAD

**Issue by hansemannn** [wordpress-mobile/AztecEditor-iOS#1260]
**Is your feature request related to a problem? Please describe.**
We would like to know if there is an ability to generate links automatically when written / pasted in the editor view.

**Describe the solution you'd like**
When a link is written / pasted in the editor view, the editor should generate a HTML link automatically or (e.g. by exposing a delegate method that asks to handle it or not).

**Describe alternatives you've considered**
Track the input manually and manipulate / replace the content.

**Comment by SergioEstevao** [comment]
Hi @hansemannn , 

This can be implemented using the `pasteboardDelegate` property in `TextView` class by implementing the `TextViewPasteboardDelegate` protocol. By default, the Aztec library provides an implementation class called `AztecTextViewPasteboardDelegate` that creates links when the content pasted is an URL object.

You can see this in action by going to Safari and press the share button and select the action Copy. If you then paste on the demo app you will see that a link will be automatically created.

If you wish to extend this to any text/string that maybe an URL you can inherit from the `AztecTextViewPasteboardDelegate` and override the `tryPasting` method to implement an extra action that will try to convert the text to an URL and create the necessary link.

You can also contribute to the project by submitting a PR that updates the `AztecTextViewPasteboardDelegate` class to provide this functionality.

**Comment by hansemannn** [comment]
Thanks Sergio! Thats already great, but I meant a slightly different behavior: Linkify'ing a link while it is typed. It can likely be done by using the UITextViewDelegate textDidChange selector, so maybe I can get a new feature out of it!
