### ISSUE TITLE
Attachments: Video Support

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#165]
Let's add Video Support for Attachments!

**Comment by SergioEstevao** [comment]
I will start implementing this assuming the use of the ```<video>``` tag at the moment.
In a second phase we will need to look at implementing through  shortcodes: ```[wpvideo]``` for video press and ```[video]``` for regular wp.org.

**Comment by jleandroperez** [comment]
Updating the milestone to Beta 1!
