### ISSUE TITLE
Review Tab functionality on external keyboards

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/AztecEditor-iOS#220]
* When in a bulleted list, tab & shift-tab should control indentation. Maybe even quote blocks?
* When not in a bulleted list we should probably eat tabs and not have it produce any spaces/tab characters.
* Review overall tab usage and make sure the key operates as expected.

**Comment by iamthomasbishop** [comment]
Another note: when the user is writing a title and hits tab, the cursor should proceed to the body of the post (which would match how it works in Calypso). @astralbodies

**Comment by jleandroperez** [comment]
Update:
1. When editing a list: pressing Tab / Shift Tab already increases / decreases the indentation level.
2. When not editing a list, pressing tab actually inserts a tab space.

All good, closing this since it's been already addressed via #586
