### ISSUE TITLE
Paragraphs/Line Breaks are missing

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/AztecEditor-iOS#274]
In Calypso, hitting Enter creates a paragraph break with space between paragraphs.
When I open that post in Aztec, the paragraph breaks are completely gone. There aren’t any line breaks between the different paragraphs I created in Calypso:

**Comment by diegoreymendez** [comment]
Isn't this ticket a duplicate of #64?

**Comment by diegoreymendez** [comment]
This is no longer an issue since the DOM structure removal.
