### ISSUE TITLE
Underline tag used  in calypso doesn't import style in Aztec

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/AztecEditor-iOS#278]
In Calypso the underline tag is implemented using the following:

` <span style="text-decoration: underline;">underlined text</span> `

Because we use the `<u>` tag this is simple ignored.

**Comment by diegoreymendez** [comment]
This issue has a dependency on #285 .

**Comment by jleandroperez** [comment]
@SergioEstevao is this issue closed by #391?

**Comment by diegoreymendez** [comment]
Closing this issue.
