### ISSUE TITLE
Support for image captions

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/AztecEditor-iOS#281]
Aztec currently does not support captions; the caption shortcode is displayed in plain text:

![photo 15-02-2017 19 32 40](https://cloud.githubusercontent.com/assets/8658164/22992275/212218fc-f3b7-11e6-9beb-dd8ce7bb0be2.png)

For comparison:

In the Visual editor, the `caption` shortcode was supported by displaying the caption in small, italic text below the image:

![photo 15-02-2017 19 41 34](https://cloud.githubusercontent.com/assets/8658164/22992280/23b59382-f3b7-11e6-899d-476b1c2ee487.png)

In Calypso, the caption is displayed in a smaller font with a blue background:

![screen shot 2017-02-15 at 7 43 39 pm](https://cloud.githubusercontent.com/assets/8658164/22992273/1b868446-f3b7-11e6-9a2f-c14a9b132b56.png)

Tested on iPad Mini, iOS 10.2.1, WPiOS 7.0.0.20170214

**Comment by diegoreymendez** [comment]
@rachelmcr - Just tagged this as v2, since shortcodes are on hold for now.  At least until we can deliver the higher priority fixes and features.

That said I'm looking forward to revisiting the priority of shortcodes as soon as the base work is complete (and ideally for inclusion in v1).

**Comment by diegoreymendez** [comment]
As a side note, this issue is related to #115, where we should (at some point) come up with a list of higher priority shortcodes we want to include.

**Comment by KokkieH** [comment]
Had a request for this via [Twitter](https://twitter.com/Kyle_Gunn97/status/889060199314714625)

**Comment by ChrissiePollock** [comment]
Another internal request - #216185-h

**Comment by diegoreymendez** [comment]
Here's a an example of a successful `caption` shortcode conversion by WordPress.

Shortcode:

```
[caption id="attachment_6" align="alignright" width="300"]<img src="http://localhost/wp-content/uploads/2010/07/800px-Great_Wave_off_Kanagawa2-300x205.jpg" alt="Kanagawa" title="The Great Wave" width="300" height="205" class="size-medium wp-image-6" /> The Great Wave[/caption]
```

HTML:

```
<div data-shortcode="caption" id="attachment_6" style="width: 310px" class="wp-caption alignright"><img src="https://i2.wp.com/localhost/wp-content/uploads/2010/07/800px-Great_Wave_off_Kanagawa2-300x205.jpg" alt="Kanagawa" title="The Great Wave" width="300" height="205" class="size-medium wp-image-6" /><p class="wp-caption-text">The Great Wave</p></div>
```

**Comment by diegoreymendez** [comment]
Shortcodes support is not very relevant to Aztec, since shortcodes are not really standard HTML.  Such support must be offered by the apps using the library.

I've opened an issue in WPiOS to keep track of this feature, and will close this issue for now.
