### ISSUE TITLE
Switch the license to MIT.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#424]
As mentioned by @astralbodies, we should be switching our license to MIT-only (pending confirmation below by @astralbodies).

Same issue for Android [here](https://github.com/wordpress-mobile/AztecEditor-Android/issues/316).

/cc @0nko

**Comment by astralbodies** [comment]
Closing for now per discussions.

**Comment by cerupcat** [comment]
Any update on this? I don't see how we can integrate into our codebase if it's GPL.
