### ISSUE TITLE
TextView: Technical Debt

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#430]
### Paragraph Formatters:
We've got the following methods that would remove the Paragraph Formatters, for a given set of conditions. If possible, analyze and simplify all the things:

```
private func ensureRemovalOfParagraphAttributes(from typingAttributes: [String: Any]) -> [String: Any]
private func ensureRemovalOfParagraphAttributes(insertedText text: String, at range: NSRange) -> Bool
private func shouldRemoveParagraphAttributes(insertedText text: String, at location: Int) -> Bool
```

### Newline LayoutManager Workaround:
Whenever a formatter requires to be rendered, even when the current line is empty, we've implemented a "Newline Insertion" mechanism, that would force the layout manager to render such a line. If possible, simplify the following:

```
private func ensureInsertionOfNewline(beforeInserting text: String)
private func ensureInsertionOfNewlineWhenEditingEdgeOfTheDocument()
private func insertNewLine()
```

Possible logic would be:

```
(position == 0 || position - 1 == \n) && position == EOF && isParagraphFormatterEnabled()
```

cc @diegoreymendez

**Comment by diegoreymendez** [comment]
@jleandroperez - I'd consider closing this for now.  The changes are applied recently basically split the logic for each case and I'm not sure there's much to gain from attempting to unify the logic.

**Comment by jleandroperez** [comment]
Sounds good Diego, closing this for now. Thanks!!
