### ISSUE TITLE
Retain empty paragraphs

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-iOS#451]
Empty paragraphs are removed after saving. There is a mobile request that we keep them:

![image](https://cloud.githubusercontent.com/assets/1522856/25433416/99f99d56-2a88-11e7-980e-673922d6d975.png) ![image](https://cloud.githubusercontent.com/assets/1522856/25433424/9f7276f4-2a88-11e7-8b51-01721b77e996.png)

**Comment by diegoreymendez** [comment]
This issue should not be started until #447 is completed.

**Comment by diegoreymendez** [comment]
Solved.

**Comment by diegoreymendez** [comment]
Fix had to be rolled back.

**Comment by diegoreymendez** [comment]
This has been solved already.
