### ISSUE TITLE
Loosing Header Style after Return

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#466]
### Steps:
1. Launch the Sample Demo (w/text)
2. With the caret at the initial position (0, 0), hit return

As a result, the h1 style will be lost.

**Comment by diegoreymendez** [comment]
@jleandroperez - Beta 2 is closed (and never saw the light of day, since the deadline wasn't met).  Switching this to beta 3.

**Comment by diegoreymendez** [comment]
@jleandroperez - I'm not sure why this was an issue: the header style is supposed to be lost when enter is pressed (Calypso also behaves like this).

**Comment by SergioEstevao** [comment]
Agree with @diegoreymendez here, header styles are lost after a newline is inserted, or are you saying that the line that had the style looses it?

**Comment by jleandroperez** [comment]
This issue was about: H1 style being removed from the H1 line, after hitting return at the location=0.

Closing this, since i can no longer repro this bug. Thanks gentlemen!!
