### ISSUE TITLE
The default paragraph style is sometimes lost.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#485]
While editing, the default paragraph style is sometimes lost, as can be seen in the smaller text near the bottom of the following screenshot:

![img_0029](https://cloud.githubusercontent.com/assets/1836005/26638115/b4837536-45f7-11e7-9154-123c31f6624f.png)

Thanks to @catehstn for reporting.

**Comment by jleandroperez** [comment]
Closing this one as cannot repro. Probably solved via #758.

Thanks!

**Comment by diegoreymendez** [comment]
Agreed on #758.  Tagging this.
