### ISSUE TITLE
VideoAttachment: Fix VideoPress ID

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#539]
VideoAttachment is not storing the VideoPressID identifier anywhere. We'll need to implement a mechanism that would populate the `namedAttributes` collection, so that the host app can read this value.

**Comment by SergioEstevao** [comment]
Is this not solved? or this is for us to implement a more generic solution?

**Comment by diegoreymendez** [comment]
@jleandroperez - Can you add a description to this issue?  Just enough so I can report what was fixed when this is closed.

**Comment by jleandroperez** [comment]
This was the reason why we had issues building the latest Aztec <> WPiOS integration. I've quickly hacked it (wired the namedAttributes collection) so that we could build the WP project, but remains broken, since we're not really populating that collection.

@SergioEstevao @diegoreymendez description updated!

**Comment by SergioEstevao** [comment]
@diegoreymendez so do you want to use the nameProperties attribute and fill it and set it has before? or do we and allow to set the HTMLRepresentation attributes directly?

It will also be worth to consider to add HTMLProperty attribute directly to TextAttachments.

**Comment by jleandroperez** [comment]
(IMHO) ideally the HTMLRepresentation is only used by the "HTML Tree Generator" / "Output Converter". I wouldn't mix "TextKit Code" with html lookups.

**Comment by SergioEstevao** [comment]
So you thinking using the nameProperties will be the best approach? and
then when are outputting we combine whatever is in the nameProperties with
the HTML attributes?

**Comment by diegoreymendez** [comment]
Can we offer a specific property for the values that need to be edited?  In this case, can't we just have a VideoPressID property users can edit?

**Comment by jleandroperez** [comment]
@SergioEstevao open to suggestions! i only opened this issue so that we keep track of this pending, but it definitely requires some thought, still.

(Serialization isn't picking up the `namedAttributes` as of now).

**Comment by jleandroperez** [comment]
@diegoreymendez thing with adding a `VideoPressID` property was: it's WordPress specific. That was the reasoning behind a collection of `userInfo` attributes

**Comment by SergioEstevao** [comment]
Also my problem with specific properties, is that if we want to do a kind of generic html editor, we cannot predict what attributes users/developers will want to edit.

For example I want to add data-wpvideopress, but other user may want to edit alt, title, id , etc.. attributes. 

That is why I 'm suggesting a generic approach that allow users of the library edit what they need.

**Comment by diegoreymendez** [comment]
The `userInfo` approach sounds reasonable to me.  If that approach works for everyone let's move forward in that direction.
