### ISSUE TITLE
Lists stop rendering bullets after emoticons are added.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#546]
Lists seem to stop rendering bullets after emoticons are added to them.

![screen shot 2017-06-21 at 11 28 14 am](https://user-images.githubusercontent.com/1836005/27389626-401f09ba-5675-11e7-9c86-2993c5b76d30.png)
![screen shot 2017-06-21 at 11 28 18 am](https://user-images.githubusercontent.com/1836005/27389628-419d1aca-5675-11e7-8644-a774e956a8e3.png)

**Comment by jleandroperez** [comment]
Sample HTML that triggers this:

```
<ol>
  <li><strong>Revenue:</strong> &#xA0;&#x1F4B0;</li>
  <li><strong>Growth:</strong> &#xA0;&#x1F4C8;</li>
  <li><strong>Engagement:</strong> &#xA0;&#x1F48D;</li>
</ol>
```
