### ISSUE TITLE
Review spacing of lists, paragraphs and blockquotes.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#547]
These elements should have more spacing after them than regular lines.  They have to be pleasing to read.

![asd](https://user-images.githubusercontent.com/1836005/27389846-020a8b94-5676-11e7-805b-fc614c93d379.png)

**Comment by SergioEstevao** [comment]
This should be simple to, it's a matter of defining the paragraphSpacing before and after. Any values/metrics in mind? Should we copy what we have on the hybrid editor?

**Comment by diegoreymendez** [comment]
Well, we'd need to define some defaults, but it should be possible to override them too.

**Comment by rachelmcr** [comment]
This is coming up in user feedback, as users expect to see spaces in between paragraphs and find it hard to read their posts and confirm that the paragraph spacing is working. (Internal ref: 206218-h, 203598-h)

**Comment by SergioEstevao** [comment]
@rachelmcr is the comments regarding visual mode? or html mode? If it's visual mode do you think just making the paragraph spacing larger will solve the issue?

**Comment by rachelmcr** [comment]
It's in visual mode. Increasing the spacing before/after paragraphs should solve the issue.

Here's how the paragraph spacing looks in the hybrid editor's visual mode:

![2017-07-21 12 16 30](https://user-images.githubusercontent.com/8658164/28461476-aae395b2-6e0e-11e7-8957-20d4c92e12b6.png)

And this is the spacing for the same post in Aztec's visual mode:

![2017-07-21 12 16 48](https://user-images.githubusercontent.com/8658164/28461480-ae9406ba-6e0e-11e7-952d-82a522f9cea3.png)

At a minimum, I would expect more spacing between paragraphs than what you see for a single line break. It doesn't have to exactly match the spacing in the hybrid editor but that's closer to what I'd expect to see.

**Comment by ChrissiePollock** [comment]
Also brought up in #219569-h

**Comment by charliescheer** [comment]
I think this is another instance of this problem, I wanted to make mention of it because they specifically mentioned that it was hard to read Chinese with the spacing problems #220698-h

**Comment by diegoreymendez** [comment]
Thank you, @charliescheer.

I've changed this issue to high priority.
