### ISSUE TITLE
Links are not underlined in the Editor 

### ISSUE THREAD

**Issue by 00travelgirl00** [wordpress-mobile/AztecEditor-iOS#568]
### Expected behavior
Links are underlined and easy to catch

### Actual behavior
Links are not underlined. Problem to  see a link, when a person is colorblind or the screen is harder to see (bright sunlight, low brightness of the screen, ...) 

### Steps to reproduce the behavior
Create a link in the editor

##### Tested on [device], iOS [version], Aztec [version]
Iphone 5s

**Comment by diegoreymendez** [comment]
Thank you for the report.

**Comment by diegoreymendez** [comment]
For future reference, this can be configured by client apps by modifying `UITextView`'s `linkTextAttributes` property.  This makes it possible for client apps to modify the link styling.

That said, we're still going to default to links having underlines for accessibility reasons.

**Comment by designsimply** [comment]
Tested and confirmed that links are underlined with a WordPress.com site using WPiOS 8.2.0.20170731:

<img alt="screen shot 2017-08-01 at tue aug 1 3 06 45 pm" src="https://user-images.githubusercontent.com/1119271/28847191-94882c18-76cb-11e7-9ed1-571293ef0981.png" width="270" />
