### ISSUE TITLE
Attachment objects should be inmutable.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#574]
Attachment objects are currently accessible from outside of Aztec's TextView through several delegates.

This represents a problem because for any change made directly to an attachment, we're unable to offer undo support.

We should consider changing our delegates to offer a different interface for editing attachments that takes care of proper undo support.  One of the possibilities is making our attachments inmutable.

/cc @SergioEstevao

**Comment by SergioEstevao** [comment]
I agree with the idea in principle, one of the obstacles is that the base object for attachments is mutable: NSTextAttachment.

We can force the properties of our derived classes to be "get" only, and force our contractors to be mandatory.

Then we could add a method to TextView called:

```updateAttachment(withID: , withNewAttachment:)```

**Comment by diegoreymendez** [comment]
We currently have a pretty decent solution designed by @jleandroperez to handle attachments.  I'm closing this issue for the time being as this is really not something we're sure about.
