### ISSUE TITLE
Add PRE tag support.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#575]
We currently do not support PRE tags.  Whitespace is relevant inside these.

To test:

1. Go to the HTML editor and paste this.

```
<pre>line 1
line 2
line 3</pre>
```

2. Switch to visual mode and back to HTML.  Make sure all whitspace is unmodified.

**Comment by SergioEstevao** [comment]
This is currently support on Aztec, the only thing happening at the moment is that the pre tag are not being merged together. So the end result ends being like this:
```
<pre>line 1</pre>
<pre>line 2</pre>
<pre>line 3</pre>
```

**Comment by diegoreymendez** [comment]
I'll close this issue for now, and we can open more specific ones if necessary.

The merging logic is a bit of a hack for all paragraph styles right now, so I wouldn't worry about this one specifically.
