### ISSUE TITLE
Attributes in "li" nodes may be lost.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#578]
### Description:

Attributes in `<li>` nodes are lost when exporting HTML.

### Details & background:

List details are currently stored in instances of class `TextList`, inside `ParagraphStyle.properties` (`ParagraphStyle` is a customizable replacement for standard `NSParagraphStyle` in `NSAttributedString`).

The problem we have is that, while we're currently saving the HTML representation of `<ul>` and `<ol>` nodes in the `TextList` instances, we're not doing the same for `<li>` nodes.

We need to figure out an adequate location and mechanism to store this information.

**Comment by arisun** [comment]
I would like contribute on this project. Can I start with this issue ?

**Comment by diegoreymendez** [comment]
Sure @arisun !

I'll add some details to the issue, though.

**Comment by diegoreymendez** [comment]
Done.  Let me know if there's anything I can help you with.

**Comment by diegoreymendez** [comment]
@arisun - This may not be the easiest first issue to tackle, so if you prefer me to give you some help picking one, just let me know.

**Comment by arisun** [comment]
Thanks @diegoreymendez . It will be very helpful if you could provide some help selecting the  first one.

**Comment by arisun** [comment]
Not able to compile the project. showing "Command failed due to signal: Segmentation fault: 11" on Aztec framework.

**Comment by diegoreymendez** [comment]
@arisun - Could you join the WordPress.org Slack server?  (instructions here: https://make.wordpress.org/chat/)

The channel is #mobile and my handle is @diegoreymendez.

It'd make it so much easier to interact, and it would be good to avoid chat noise in this issue.  Thanks!

**Comment by diegoreymendez** [comment]
As reported by @koke here:

When Aztec opens a gallery from Gutenberg and saves it's stripping the `class` attribute from each list item, breaking the gallery block.

It's turning this:

```
<!-- wp:gallery -->
<ul class="wp-block-gallery alignnone columns-1 is-cropped">
    <li class="blocks-gallery-item">
        <figure><img src="https://sandbox.koke.me/wp-content/uploads/2018/05/fullsizeoutput_52f7.jpeg" alt="" data-id="96" /></figure>
    </li>
</ul>
<!-- /wp:gallery -->
```

Into this:

```
<!-- wp:gallery -->
<ul class="wp-block-gallery alignnone columns-1 is-cropped">
  <li>
    <figure><img src="https://sandbox.koke.me/wp-content/uploads/2018/05/fullsizeoutput_52f7.jpeg" class="alignnone" data-id="96" alt=""></figure>
  </li>
</ul>
<!-- /wp:gallery -->
```

**Comment by diegoreymendez** [comment]
Fixed by https://github.com/wordpress-mobile/AztecEditor-iOS/pull/985
