### ISSUE TITLE
Improve video interaction on the editor

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/AztecEditor-iOS#580]
### Expected behavior

When tapping on videos the behaviour should be similar to images, in a way that we show options to edit/remove or play

### Actual behavior

When tapping a video the app immediately starts to reproduce the video

### Steps to reproduce the behavior

- Start the demo app
- Open the demo with content.
- Scroll to video and tap on it.

**Comment by diegoreymendez** [comment]
Resolved.
