### ISSUE TITLE
Copy + Paste: Strip HTMLRepresentation Elements

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#627]
Due to Crash #626, we'll be releasing Aztec Beta 8.1 with a hotfix: HTMLRepresentation will be stripped from the Pasteboard.

This will be later re-enabled with support for the new entities.

**Comment by jleandroperez** [comment]
@diegoreymendez @SergioEstevao ready for another look

Sergio: Thanks so much for catching the **Cut** crash as well!!

**Comment by diegoreymendez** [comment]
Closing this, as it's merged already.
