### ISSUE TITLE
RTL support when switching to HTML

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/AztecEditor-iOS#631]
### Expected behavior
I expect to be able to type in Arabic and switch to HTML and back without issues.

### Actual behavior
Strange things happen:
![arabicandhtmlswitch](https://user-images.githubusercontent.com/5558824/28388172-31892d10-6ca8-11e7-9d86-d2f2b4716dce.gif)

### Steps to reproduce the behavior

1. On XCode set the scheme to use pseudo RTL language
2. On the simulator add the Arabic keyboard
3. Create a new post using Aztec, with the Arabic keyboard type some text.
4. Switch to HTML

##### Tested on simulator, iOS 10.3, Aztec 1.0.0-beta.8

**Comment by SergioEstevao** [comment]
@jleandroperez I think this results from our encoding of html entities...What do you think?

**Comment by diegoreymendez** [comment]
A few notes on this:

1. This is not related to RTL at all.  This happens for [Chinese too](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/298), and is most likely related to the encoding logic in libxml2.
2. I've tried fixing this by changing our base encoding from UTF8 to UTF16 but that was both a painful change and proved not do really fix much at all.
3. We should unify this issue and #298 into a single issue.

**Comment by diegoreymendez** [comment]
Also: this is not really breaking anything, it's just encoding certain characters to their unicode value.

So while this must be totally annoying for people using Arabic and English, at least it won't cause any data loss.

**Comment by diegoreymendez** [comment]
To avoid editing an issue I did not create, I'm closing both of the referenced issues to unify them in #632.
