### ISSUE TITLE
Stop encoding non-latin characters in HTML Mode

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#632]
### Description:

We're currently encoding many non-latin characters when switching to HTML mode.

### Details:

This issue was created by unifying #298 (Chinese) and #631 (Arabic).

This is an example provided by @elibud showing how Arabic characters are encoded when switching to HTML mode:

![arabicandhtmlswitch](https://user-images.githubusercontent.com/5558824/28388172-31892d10-6ca8-11e7-9d86-d2f2b4716dce.gif)

### Steps to reproduce the behavior

1. On XCode set the scheme to use pseudo RTL language
2. On the simulator add the Arabic keyboard
3. Create a new post using Aztec, with the Arabic keyboard type some text.
4. Switch to HTML

### Tested on simulator, iOS 10.3, Aztec 1.0.0-beta.8

**Comment by designsimply** [comment]
Tested and confirmed non-latin characters are not html-encoded when switching from visual to HTML mode in the Aztec editor:

<img alt="img_1391" src="https://user-images.githubusercontent.com/1119271/28850088-bddc98b8-76d7-11e7-8dd6-a4da097907c8.PNG" width="270" />
<sup>Tested with madefortesting.com running WP 4.9 and JP 5.2 hosted at Bluehost using iPhone 6S, iOS 10.3.3, WPiOS 8.2.0.20170731.</sup>

Note: I used [Google Translate](https://translate.google.com/#en/ar/She%20walks%20in%20beauty%2C%20like%20the%20night%20%0AOf%20cloudless%20climes%20and%20starry%20skies%3B%20%0AAnd%20all%20that%E2%80%99s%20best%20of%20dark%20and%20bright%20%0AMeet%20in%20her%20aspect%20and%20her%20eyes%3B%20%0AThus%20mellowed%20to%20that%20tender%20light%20%0AWhich%20heaven%20to%20gaudy%20day%20denies.) to copy text per <a href="http://www.makeuseof.com/tag/type-non-latin-characters-without-language-packs/">a suggestion I found online</a>.

**Comment by jleandroperez** [comment]
Thanks for helping us out @designsimply !!

**Comment by kriskarkoski** [comment]
I was seeing this issue in 8.1.1 when a post was Publicized to Facebook. I updated to 8.2 and confirmed it's no longer happening. Thanks for the fix!

**Comment by ChrissiePollock** [comment]
User on 8.2 has this issue in email notifications #216440-h

**Comment by diegoreymendez** [comment]
@ChrissiePollock - Do you think it'd be possible to gather enough information to open a new issue (and for us to replicate this behavior)?

Feel free to DM me, if you prefer a faster loop and / or need assistance.
