### ISSUE TITLE
HTML Entities for Punctuation

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/AztecEditor-iOS#660]
Users are reporting some issues with HTML entities in Aztec. I’ve seen two different cases:

HTML entities showing up in email notifications or publicized posts (e.g. apostrophes or quotation marks replaced with their HTML entities there).
HTML entities breaking or messing up shortcodes, e.g. contact forms and recipes, because the quotation marks within the shortcodes are replaced.
Here’s an example of a contact form that has HTML entities showing up after updating it in Aztec: https://rachelmtestblog.wordpress.com/contact/

Here’s what I see in the editor:

![2017-07-26-12-20-38](https://user-images.githubusercontent.com/651601/28622605-0ea97236-720d-11e7-8da8-d6e09daf9989.png)
![2017-07-26-12-20-31](https://user-images.githubusercontent.com/651601/28622608-1196dfc4-720d-11e7-92e1-55fcda3c4adc.png)

**Comment by jleandroperez** [comment]
Closed via #661. Thanks Sergio!!

**Comment by designsimply** [comment]
Tested with the following steps and everything looks good:

1. Publish a page containing a contact form.
1. Open the page in WPiOS 8.2.0.20170731.
1. Toggle back and forth between the HTML and visual editors and look for any oddities with encoding.

<strong>Result:</strong> didn't see any encoding problems.

<img alt="img_1397" src="https://user-images.githubusercontent.com/1119271/28854533-edb7bdd4-76f4-11e7-9ee7-76c9e113090c.PNG" width="270" />
<sup>Tested with madefortesting.com running WP 4.9 and JP 5.2 hosted at Bluehost using iPhone 6S, iOS 10.3.3, WPiOS 8.2.0.20170731.</sup>
