### ISSUE TITLE
Add an explicit CHANGELOG.md 

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/AztecEditor-iOS#664]
Every time a PR is created for an improvement/feature enhancement lets add an explicit line to a CHANGELOG.md file. Use [this format](http://keepachangelog.com/en/1.0.0/) for guidance.

cc: @diegoreymendez @SergioEstevao @jleandroperez

**Comment by diegoreymendez** [comment]
We need to reboot this.  I think it could be interesting to add some sort of automated check for this as well (make sure there's a diff in CHANGELOG.md when a PR is submitted).

**Comment by SergioEstevao** [comment]
Since version 1.13.0 I reinstated the support for a changelog file. 
The ideas is people that are doing PR should add the necessary information on the CHANGELOG.md file.
