### ISSUE TITLE
Any plan for React Native?

### ISSUE THREAD

**Issue by musicode** [wordpress-mobile/AztecEditor-iOS#697]
As you know, Rich text editor is difficult to write, I have search all react native components for 2 years, unfortunately I did not found it.

Aztec Editor is an ios and android editor, so it is perfect for react native.

So I want to know do you have any plan for react native?

**Comment by diegoreymendez** [comment]
Not as part of this project at least, since Aztec was specifically designed as a Swift library.

If anyone decides to write a React Native wrapper for Aztec that'd be a separate project.
