### ISSUE TITLE
Text coloring support

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#703]
We had a regression and text-coloring no longer works.  We need to get it back into Aztec.
 
Edit: for the scope of this issue it's enough to make sure that text coloring is maintained in the HTML <-> CSS conversions.

There's no need to add UI element to the format bar at this time.

**Comment by shahla00** [comment]
@diegoreymendez , I'm starting to look into this. Is the preference to build a color palette from scratch, or use one of the libraries out there?

**Comment by diegoreymendez** [comment]
@shahla00 - For the scope of this issue we should just make sure text-coloring support is maintained in the visual <-> html conversions.

The UI elements for picking a font color should be implemented by the client App (in our case the Example app, although adding that is secondary at this time).

For some more context: I think our format bar shouldn't really be part of Aztec in the long run.
