### ISSUE TITLE
HeaderFormatter: Back Delete should merge Header Styles

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#708]
1. Enter two paragraphs (h1 + h2):
  ```
  <h1>Header 1 </h1>
  <h2>Header 2 </h2>
  ```
2. Back delete just before `Header 2`

As a result, the text font on Header 2 should switch to Header 1 font size. Aztec currently ends up rendering a single paragraph but with both fonts size applied.

Props to @SergioEstevao for spotting this!

**Comment by diegoreymendez** [comment]
@jleandroperez - Some extra information for clarity: the `NSParagraphStyle` string attribute is fixed when [`fixParagraphStyleAttribute()`](https://developer.apple.com/documentation/foundation/nsmutableattributedstring/1527082-fixparagraphstyleattribute) is executed.

I think we need to start by checking if that method is being executed at all.
