### ISSUE TITLE
Japanese text issues when switching between Visual and HTML modes

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/AztecEditor-iOS#709]
There appears to be a few issues while entering multibyte text (in this case Japanese) into Aztec.

![japan_text](https://user-images.githubusercontent.com/154014/29690176-8ffcd810-88eb-11e7-8e7e-b2852b9d12dc.gif)

### Steps to reproduce the behavior
There are two potential issues here.
 
👉  Tapping enter in HTML mode while multibyte text exists clears it:

0. Make sure Japanese - Kana keyboard is active.
1. Run the editor demo and enter some random text.
2. Switch to HTML mode and hit the return button in the lower right of the keyboard.
3. Notice the text disappears
4. Switch to visual mode — notice the text returns.
5 Switch to HTML mode — notice the text is fine.

👉 Adding additional multibyte text in HTML mode can scramble previous text:

0. Make sure Japanese - Kana keyboard is active.
1. Run the editor demo and enter some random text.
2. Switch to HTML mode and hit the return button in the lower right of the keyboard.
3. Notice the text disappears
4. Switch to visual mode — notice the text returns.
5. Switch to HTML mode — notice the text is fine.
6. Paste some additional multibyte text into the editor (e.g. 私はものが好き)
7. Tap the return button and notice how the preceding text becomes scrambled.
8. Switch modes again (HTML -> Visual -> HTML) and see that the text is restored.

Note that there are a few other ways to trigger the previous text getting scrambled in HTML mode - this is just one example.

##### Tested on iPhone 7+ and Sim, iOS 10.3.3, Aztec `develop`

**Comment by maxme** [comment]
@diegoreymendez  this one seems pretty bad to me, should we bump it to high priority?

**Comment by diegoreymendez** [comment]
@maxme - Definitely.  I somehow missed this issue.

**Comment by diegoreymendez** [comment]
I managed to reproduce these issues, and also discovered it seems these issues are caused by the code that adds color to HTML tags in HTML mode.

Adding a `return` statement right after this line fixes the problems: https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Aztec/Classes/TextKit/HTMLStorage.swift#L125

**Comment by diegoreymendez** [comment]
Commenting this specific line fixes the problem:

https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Aztec/Classes/TextKit/HTMLStorage.swift#L129

It seems our code to set the default font style is at odds with languages that don't like our default font.

**Comment by diegoreymendez** [comment]
Due to the severity of this issue a second PR was created to release the fix in 1.0.0-beta.14.1.
