### ISSUE TITLE
iOS 11 losing styles after typing 1 character

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#725]
When using Aztec in iOS 11, styles are being lost after typing just 1 character.

How to test:

1. Open the empty editor.
2. Type a regular first line.
3. Press enter
4. Enable any style.
5. Start typing.

Expected behavior: the full line should have the selected style.
Current behavior: after the first character is entered, the style is removed.

**Comment by diegoreymendez** [comment]
Reported as a `UITextView` issue to Apple (Apple ref 34546954).

I've also created [an example minimal project](https://cloudup.com/c8rCpGokxGS) demonstrating this issue is not caused by our code.

**Comment by jleandroperez** [comment]
Closed via #726
