### ISSUE TITLE
Aztec: Crash on drag and drop in iOS 11

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/AztecEditor-iOS#727]
### Details:

Props to @frosty for spotting this one!. Parent WPiOS [Issue Here](https://github.com/wordpress-mobile/WordPress-iOS/issues/7617).

```
1. Open Aztec, and Safari side-by-side
2. Open a web page with images
3. Drag one image into Aztec
4. Tap to the right of the image, and type a new line (enter)
5. Drag another image (or the same one) in again, into the new space
6. Crash.
```

--

<img width="1194" alt="screen shot 2017-09-22 at 11 26 14 am" src="https://user-images.githubusercontent.com/1195260/30749159-ef9489d6-9f88-11e7-8222-bc146e172988.png">

**Comment by jleandroperez** [comment]
Reopening this one. We've got reports that it's still happening, with a low occurrence rate (2 over 25 copy + paste OP's).

**Comment by diegoreymendez** [comment]
@jleandroperez - In order to validate the reports, can you provide additional info as to what triggered the reopening of the issue?

It'd also be important to know what iOS / WPiOS version this was tested against.

**Comment by jleandroperez** [comment]
WPiOS 8.5.2 (which came with Aztec 12 bundled in) + iOS 11

**Comment by jleandroperez** [comment]
Closing in favor of #771. The issue reported was actually a Copy + Paste crash, not a drag and drop one, apologies!
