### ISSUE TITLE
Layout issues on iPhoneX

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/AztecEditor-iOS#728]
### Expected behaviour

The editor should show content correctly on iPhone X and the text toolbar should take account the new margins.

### Actual behaviour

Some of the editor content is overlapped by the notch on landscape mode.

### Steps to reproduce the behavior

- Start the demo app on iPhoneX
- Open the editor with content
- See something like this:

<img width="964" alt="screen shot 2017-09-25 at 12 52 57" src="https://user-images.githubusercontent.com/651601/30807422-a638b454-a1f1-11e7-8fa7-4c426e912cfb.png">

**Comment by jleandroperez** [comment]
Closed via #732 by @SergioEstevao.

Tested in develop / iOS 11 / iPhone X. Looking smooth!
