### ISSUE TITLE
No Bold and Italic effect for Chinese characters

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#737]
### Expected behavior

Can apply **Bold** trait for Chinese characters 

### Actual behavior

No effect when applying **Bold** trait   for Chinese characters

### Steps to reproduce the behavior

1. Input any Chinese characters(Like `你好`) in Aztec Demo's TextView
2. Select them and apply **Bold**

##### Tested on iPhone 7, iOS 11, Aztec 1.0.0-beta.11

**Comment by azone** [comment]
I found an alternative solution for italic in StackOverflow:  https://stackoverflow.com/questions/21009957/italic-font-not-work-for-chinese-japanese-korean-on-ios-7

**Comment by diegoreymendez** [comment]
The italic part of the issue is still open.  That said... I'm not sure we should try to support italic for fonts that don't offer support for it.

Maybe the correct solution is using a diferent default font?

**Comment by diegoreymendez** [comment]
@azone - I've modified the description of this issue to refer to **bold** styling only.  The italic part will continue in [a separate issue](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/762) for organizational purposes.
