### ISSUE TITLE
Feedback/Beta label causes layout issues when text label is long

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/AztecEditor-iOS#739]
### Expected behavior

Text label in English is short ("Feedback"), thus leaving a fair amount of space for title with wrapping.

### Actual behavior

In some translations, text label can get very long, causing issues with the title layout.

![simulator screen shot sep 22 2017 13 19 45](https://user-images.githubusercontent.com/1200432/31024656-64dc0a44-a505-11e7-86fa-99d57e196d41.png)

**Comment by iamthomasbishop** [comment]
Proposal: change the text label to an icon. The icon that makes sense at this point is probably the `?` icon. Here's what it looks like (gridicons-help-outline set in $gray color):

<img width="529" alt="screenshot 2017-09-29 10 52 11" src="https://user-images.githubusercontent.com/1200432/31024977-66640d20-a506-11e7-8ef0-d71230b59e02.png">

Note: this label will be gone in a couple weeks when Aztec becomes the default editor.

**Comment by diegoreymendez** [comment]
While not extremely relevant, I think translating "Feedback" as "Comentarios y Sugerencias" is bad in itself due to the evident amount of extra space needed for the translation.

Just "Comentarios" would've been good.  And even better if we switch to the proposed icon.

**Comment by diegoreymendez** [comment]
Moving this to WPiOS [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/7957).

Closing since this is only relevant to WPiOS.
