### ISSUE TITLE
Migrate to Swift's Codable protocol.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#746]
We're using `Coding` and `NSCodingProxy` to address some shortcomings of trying to encode and decode objects in Swift.

Recently a `Codable` protocol was introduced to address the original issues we have.

Repace the protocol we're using with `Codable`.

**Comment by diegoreymendez** [comment]
This issue was resolved by @jleandroperez [in 1.0.0-beta.13](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/782).

**Comment by jleandroperez** [comment]
Ahhhhh good ol' times!!! ❤️
