### ISSUE TITLE
Crash: HTMLStorage

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/AztecEditor-iOS#771]
Crashlytics # 59dcf11abe077a4dcc102c88
```
0  Aztec                          0x100f1b0a0 @objc HTMLStorage.init() -> HTMLStorage (HTMLStorage.swift)
1  UIFoundation                   0x190efb96c -[NSLayoutManager(NSLayoutManager_Animation) destinationTextContainerForRange:inTextContainer:] + 200
2  UIFoundation                   0x190efbf44 -[NSLayoutManager(NSLayoutManager_Animation) layoutFragmentsForReplacingCharactersInRange:withAttributedString:rect:textContainer:] + 936
3  UIKit                          0x1909f18a8 -[UITextView _performPasteOfAttributedString:toRange:animator:completion:] + 752
4  UIKit                          0x1902d4e18 -[UITextPasteController _performPasteOfAttributedString:toRange:progressSupport:animator:completion:] + 908
5  UIKit                          0x1902d42f4 __58-[UITextPasteController _executePasteForSession:animator:]_block_invoke + 336
6  libdispatch.dylib              0x186351048 _dispatch_client_callout + 16
7  libdispatch.dylib              0x18635f2a0 _dispatch_sync_thread_bound_invoke + 68
8  libdispatch.dylib              0x186351048 _dispatch_client_callout + 16
9  libdispatch.dylib              0x18635db74 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1016
10 CoreFoundation                 0x186973f20 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
11 CoreFoundation                 0x186971afc __CFRunLoopRun + 2012
12 CoreFoundation                 0x1868922d8 CFRunLoopRunSpecific + 436
13 GraphicsServices               0x188723f84 GSEventRunModal + 100
14 UIKit                          0x18fe3f880 UIApplicationMain + 208
15 WordPress                      0x100236d28 main (main.m:11)
16 libdyld.dylib                  0x1863b656c start + 4
```

**Comment by diegoreymendez** [comment]
For completeness, I believe these reports are related:

#230494-h
iPad Pro
iOS 11.0.2
WordPress 8.4 (@pmciano was unable to replicate on 8.5)

> Whenever I try to copy or paste something in HTML mode, the app invariably crashes.

#231525-h
iPhone 7 Plus
iOS 11.0.1
WordPress v. 8.5.2

> I use ios11 (also recently updated) So I am not sure if both updates play Nice or what. However, my main problem is HTML .. I switch back-and-forth between text and HTML while writing a blog post because I add centering of headings etc. that cannot be done from the text screen. However when I go from HTML back to text screen all of my photos change to curly quotes. In addition, if I attempt to copy HTML formats and then try to paste into another blog post in the HTML screen, the app crashes each and every time.
>
> The crash comes from visual editor 2.0 .. switching back to visual doesn’t crash, however the curly quotes issued exists either place.

**Comment by diegoreymendez** [comment]
@jleandroperez - Remember to mark the milestone when closing.  Thanks!

**Comment by jleandroperez** [comment]
AHHH apologies, missed that!
