### ISSUE TITLE
Unable to add a link for an inserted image

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/AztecEditor-iOS#776]
### Expected behavior
To be able to add a link for an inserted image as with the visual editor.

### Actual behavior
Images on Aztec are missing several attributes that are available on the visual editor, particularly the ability to add a link.

Visual Editor | Aztec
-|-
|![simulator screen shot - iphone 8 - 2017-10-18 at 09 50 46](https://user-images.githubusercontent.com/5558824/31719482-0186a046-b3ea-11e7-8cde-395099f56fdc.png)|![simulator screen shot - iphone 8 - 2017-10-18 at 09 51 09](https://user-images.githubusercontent.com/5558824/31719485-03294688-b3ea-11e7-9de4-7feee597b50d.png)|

### Steps to reproduce the behavior
Insert an image and tap on Edit.

##### Tested on IPhone 7, iOS 11, Aztec Beta 12

Sister issue on Android: https://github.com/wordpress-mobile/AztecEditor-Android/issues/505

Originally reported by an iOS user via [Twitter](https://twitter.com/meghancolson/status/920269753444392960).

**Comment by diegoreymendez** [comment]
Closing this issue in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/8045, since this feature needs to start in WPiOS and only eventually spawn more specific requirements in Aztec.
