### ISSUE TITLE
replaceRangeWithTextWithoutClosingTyping causes crash

### ISSUE THREAD

**Issue by winklerp** [wordpress-mobile/AztecEditor-iOS#789]
### Actual behavior
Tapping on the spacebar multiple times after entering a word causes the app to crash (looks like it is running into an endless loop in method TextView.replaceRangeWithTextWithoutClosingTyping)

### Steps to reproduce the behavior
Just enter a few words into the editor and then tap the spacebar multiple times

**Comment by ajfigueroa** [comment]
Does the following PR the issue by any chance? https://github.com/wordpress-mobile/AztecEditor-iOS/pull/784/files

**Comment by winklerp** [comment]
The PR fixes the issue in my case.

**Comment by diegoreymendez** [comment]
We're reviewing the PR to confirm.

**Comment by diegoreymendez** [comment]
This is solved by https://github.com/wordpress-mobile/AztecEditor-iOS/pull/784
