### ISSUE TITLE
"replaceRangeWithTextWithoutClosingTyping:replacementText:" usage

### ISSUE THREAD

**Issue by ajfigueroa** [wordpress-mobile/AztecEditor-iOS#790]
Could overriding this potentially be an issue when submitting for the App Store since it looks to be a private API? As seen in the private headers [here](https://github.com/nst/iOS-Runtime-Headers/blob/master/protocols/UITextInputPrivate.h#L35)

I was just curious since this does fix a major iOS 11 issue with formatting.

**Comment by ajfigueroa** [comment]
This was meant to be a question, I'm unable to edit labels.

**Comment by diegoreymendez** [comment]
We don't know yet, but it's the only way we've found to solve the issue with `typingAttributes` in `UITextView`.

**Comment by diegoreymendez** [comment]
The fix is up in our last release.
