### ISSUE TITLE
Caret and characters are not in middle of block-quote

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#792]
### Expected behavior

Caret and characters are not in middle of block-quote

### Actual behavior

If block-quote is first paragraph of TextView, caret and first line are on top of block-quote.

### Steps to reproduce the behavior

1. Clear contents of TextView
2. Press block quote button
3. Input any characters 

![img_0258](https://user-images.githubusercontent.com/164407/32161601-1e155bd4-bd91-11e7-909d-97afe3695e52.PNG)

**Comment by diegoreymendez** [comment]
Reminder: during the review validate if this fixes #789 too.

**Comment by diegoreymendez** [comment]
The first line in a paragraph uses a different spacing mechanism in iOS than the rest of the lines.  Since there's no easy way for us to make this customizable, I'm closing this issue as "won't fix".
