### ISSUE TITLE
TextView's marked text may remove block-quote

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#801]
### Expected behavior

See the video below:
[ScreenRecording_11-02-2017 10:21.zip](https://github.com/wordpress-mobile/AztecEditor-iOS/files/1436312/ScreenRecording_11-02-2017.10.21.zip)

### Actual behavior

See the Video below:

[ScreenRecording_11-02-2017 10:19.MP4.zip](https://github.com/wordpress-mobile/AztecEditor-iOS/files/1436310/ScreenRecording_11-02-2017.10.19.MP4.zip)

### Steps to reproduce the behavior

1. Add block-quote
2. Switch input method to Chinese
3. Input Chinese but do not confirm
4. block-quote may removed by continue pressing keyboard

##### Tested on iPhone 7, iOS 1, Aztec beta-14

**Comment by jleandroperez** [comment]
Some extra details:

- Keyboard: Chinese (Traditional) - Pinyin
- [Sample video here](https://cloudup.com/cWM3X_ehBlU)

On my end, i've been unable to trigger it in any TextView location (as seen in the video), nor, consistently. Would appear to be some UITextView inner management for dynamic text replacement.
