### ISSUE TITLE
How to use CocoaPods install the latest version

### ISSUE THREAD

**Issue by lixiaonan** [wordpress-mobile/AztecEditor-iOS#805]
![image](https://user-images.githubusercontent.com/13104094/32366176-f7973016-c0b7-11e7-8446-ab6dc6bc83d9.png)

**Comment by lixiaonan** [comment]
![image](https://user-images.githubusercontent.com/13104094/32366419-f0ab4ca0-c0b8-11e7-888c-e50ff1d3a7cd.png)

**Comment by diegoreymendez** [comment]
I recommend specifying the latest beta version in the pod file, which is `1.0.0-beta.13` (soon to become beta 14).
