### ISSUE TITLE
Can't input Chinese characters

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#811]
### Expected behavior

Input Chinese characters in heading as usual

### Actual behavior

Can't input Chinese characters in heading after first confirm if there is empty line before heading.
See the video below:

[ScreenRecording_11-07-2017 17:26.MP4.zip](https://github.com/wordpress-mobile/AztecEditor-iOS/files/1449413/ScreenRecording_11-07-2017.17.26.MP4.zip)

### Steps to reproduce the behavior

1. Open editor
2. Press return
3. Turn Heading on (h1 or h2, ...)
4. Input any Chinese characters and confirm
5. Continue input Chinese characters and confirm (can't  input anything in this step)

All those invisible Chinese characters will appears if rotate the device.

**Comment by jleandroperez** [comment]
### Note: 
In order to reproduce this one, please, set up the Chinese Simplified Pinyin keyboard.

Thank you!!
