### ISSUE TITLE
Heading 1~6, block-quote and list will reset undo manager

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#812]
### Expected behavior

Undo and redo can work in any situation

### Actual behavior

See video belo:
[ScreenRecording_11-07-2017 17:43.zip](https://github.com/wordpress-mobile/AztecEditor-iOS/files/1449623/ScreenRecording_11-07-2017.17.43.zip)

### Steps to reproduce the behavior

1. enter one line characters
2. enter another line characters
3. set line one to heading 1~6, block-quote or list
4. shake device and undo
5. loop step 4

You will see that, the undo manager can't undo completely.

##### Tested on iPhone 7, iOS 11, Aztec beta-13

**Comment by diegoreymendez** [comment]
@azone - We're having trouble understanding what this issue is.

Considering we can't download .zip files from external sources, can you please clarify this issue with images and a better description?

**Comment by azone** [comment]
Undo manager can't undo all steps if apply H1~6, block-quote, ordered list and unordered list
