### ISSUE TITLE
Question: Can I insert a custom UIView?  && Can I edit media touch events?

### ISSUE THREAD

**Issue by magonicolas** [wordpress-mobile/AztecEditor-iOS#826]
Hello!
It that possible to insert a custom UIView?

Can I edit what happen when user clicks an image or video?

**Comment by diegoreymendez** [comment]
There's currently no direct support to adding views in content.

This is the delegate method you can use to know when an attachment has received a single tap: https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Aztec/Classes/TextKit/TextView.swift#L60
