### ISSUE TITLE
Copy/Pasting link will change text styles

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/AztecEditor-iOS#827]
### Expected behavior

When copy/pasting links they would appear as `<a>` tags or as just same sized text (since it looks more like feature request)

### Actual behavior

Text appears smaller when pasting via `paste`
Text appears blue when pasting via CMD+P

### Steps to reproduce the behavior

- Open empty editor
- insert link via `link` button
- copy it
- paste into the editor
- try to paste with CMD+P & then paste via "iOS" way

##### Tested on iOS Simulator Iphone SE, iOS 11.1, Aztec from `add/ui-tests-for-high-priority-issues`

![screencast 2017-11-15 21-18-24](https://user-images.githubusercontent.com/5654161/32855931-e9bd88b2-ca4b-11e7-8270-1c46e3025b59.gif)

**Comment by SergioEstevao** [comment]
This is fixed on the latest versions of Aztec.
