### ISSUE TITLE
Some questions of Example

### ISSUE THREAD

**Issue by lixiaonan** [wordpress-mobile/AztecEditor-iOS#832]
When using Example, select Empty Editor Demo:
1. Choose to edit the text
2. Enter the token, then wrap
3. Select a picture and insert it
4. Wrap

In the picture upload process, you can see the continuous beating process

**Comment by lixiaonan** [comment]
![image](https://user-images.githubusercontent.com/13104094/33009100-ab40c61c-ce10-11e7-82aa-20e0972bc361.png)
This is another question

**Comment by diegoreymendez** [comment]
What's the question @lixiaonan?

**Comment by jleandroperez** [comment]
Closing this one @lixiaonan. Please, feel free to reopen, if needed.
