### ISSUE TITLE
Editing Text in Widgets Results in Jumps

### ISSUE THREAD

**Issue by ChrissiePollock** [wordpress-mobile/AztecEditor-iOS#851]
### Expected behavior
When editing a widget (ex: adding an address to a contact widget) one could tap in the box and edit the text. 

### Actual behavior
The cursor jumps around as if there is a calibration error.

### Steps to reproduce the behavior
Go to Widgets in Customizer and attempt to edit a widget such as the Contact Info & Map Widget

##### Original issue and screencast from #244974-h on https://cloudup.com/c8nrbgbIwsd

 Replicated on [iPhone SE], iOS [11.1.2], Aztec [8.9]

**Comment by jleandroperez** [comment]
@ChrissiePollock closing this one since the glitch itself happens in a Web View (not sure if it's a calypso issue, but not related to Aztec!).

**Comment by diegoreymendez** [comment]
@ChrissiePollock - It sounds like this issue could be related to WPiOS rather than Aztec.  You may want to consider moving it to https://github.com/wordpress-mobile/WordPress-iOS.
