### ISSUE TITLE
Link range issue

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#853]
### Expected behavior

TextView can detect full link range

### Actual behavior

Link range are separate by white space in Chinese characters or Emoji
For example:
[你好 世界]() will become [你好](), "[ ]()" and [世界]()

### Steps to reproduce the behavior

1. Insert a link with title `你好 世界`
2. Move caret to `你好` and edit the link
3. You will see the link editing dialog only has `你好` in link title filed

##### Tested on iPhone 7, iOS 11, Aztec 1.0.0-beta.15

**Comment by shengyang998** [comment]
Same bug. Any idea?
