### ISSUE TITLE
Text Color Support

### ISSUE THREAD

**Issue by lixiaonan** [wordpress-mobile/AztecEditor-iOS#857]
Does AztecEditor-iOS support the color of text?

**Comment by shahla00** [comment]
I believe issue 703 answers the question. It seems it was supported at some point but then that support got broken.

**Comment by diegoreymendez** [comment]
Closing, since @shahla00 's answer is correct.

**Comment by sergstav** [comment]
@shahla00 @diegoreymendez hi, so what the current situation with the colors? I see even Example project in repo ignores span with colors, can I somehow got it to work?
