### ISSUE TITLE
Italic style is broken in Arabic

### ISSUE THREAD

**Issue by shahla00** [wordpress-mobile/AztecEditor-iOS#873]
### Expected behavior
The font should be italic if the user styled it to be so.

### Actual behavior
The font is not italic when the user styled it to be so.

### Steps to reproduce the behavior
1- Make sure you are using Arabic keyboard.
2- Enter a paragraph in Arabic.
3- Select a word in the paragraph and tap on the "Italic" button.
4- Notice how nothing happens.

##### Tested on [device], iOS [version], Aztec [version]
iPhone 8 plus simulator, iOS 11.2

**Comment by shahla00** [comment]
Filed a bug with Apple as the issue turned out to be not specific to Aztec. Radar number is 36216475.

**Comment by diegoreymendez** [comment]
Thank you @shahla00!

**Comment by SiobhyB** [comment]
There was a similar report in p4a5px-26T, where a user was unable to set Chinese text to italic.

**Comment by diegoreymendez** [comment]
Unfortunately, I don't think there's much we can do on our end to resolve this issue.

We'd definitely be able to do something once Apple fixes their part of it, but in the meanwhile, I'm closing this issue as "won't fix".

Do let us know if you receive any update on your radar.
