### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by shahla00** [wordpress-mobile/AztecEditor-iOS#875]
### Expected behavior
No memory leaks

### Actual behavior
Memory leaks reported

### Steps to reproduce the behavior
Use the editor for a while and then look at the memory debugger.

##### Tested on [device], iOS [version], Aztec [version]
iPhone 8 plus simulator, iOS 11.2

**Comment by shahla00** [comment]
I already fixed one issue that dramatically reduced the leak. Still looking into more.

**Comment by shahla00** [comment]
I addressed all the memory leak issues I had identified and the PRs have been merged. The bug can be closed now, unless others have identified more leaks.

**Comment by diegoreymendez** [comment]
@shahla00 - Can you refer the PRs to this issue / or vice-versa add the links here for reference?

Thanks!

**Comment by diegoreymendez** [comment]
Ref: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/876
