### ISSUE TITLE
Can not run by CocoaPods install

### ISSUE THREAD

**Issue by CivelXu** [wordpress-mobile/AztecEditor-iOS#906]
### Expected behavior

Can not run by CocoaPods install

### Actual behavior

can normal run

### Steps to reproduce the behavior

Swift Compiler Error
too may function had error

##### Tested on [device], iOS [version], Aztec [version]
Xcode 9 Swift 4.0

**Comment by diegoreymendez** [comment]
We're integrating Aztec constantly into WPiOS without issues.  Can you please provide us with a step-by-step on how you're integrating Aztec and the verbose logs of CocoaPods when trying to run `pod install`?

**Comment by CivelXu** [comment]
Last login: Tue Feb  6 21:10:04 on ttys004
xuxiwens-MacBook-Pro:~ xuxiwen$ cd /Users/xuxiwen/Desktop/AztecEditorTest/AztecEditorTest.xcodeproj 
xuxiwens-MacBook-Pro:AztecEditorTest.xcodeproj xuxiwen$ cd ..
xuxiwens-MacBook-Pro:AztecEditorTest xuxiwen$ pod update
Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/xuxiwen/.cocoapods/repos/master fetch origin
  --progress
  remote: Counting objects: 3948, done.        
  remote: Compressing objects: 100% (239/239), done.        
  remote: Total 3948 (delta 1717), reused 1641 (delta 1641), pack-reused 2056        
  Receiving objects: 100% (3948/3948), 440.70 KiB | 25.00 KiB/s, done.
  Resolving deltas: 100% (2631/2631), completed with 718 local objects.
  From https://github.com/CocoaPods/Specs
     d3d60330e09..f4eaa0224f7  master     -> origin/master
  $ /usr/bin/git -C /Users/xuxiwen/.cocoapods/repos/master rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/xuxiwen/.cocoapods/repos/master reset --hard
  origin/master
  HEAD is now at f4eaa0224f7 [Add] FancyTextField 0.2.1
Analyzing dependencies
Downloading dependencies
Using WordPress-Aztec-iOS (0.2.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Automatically assigning platform `ios` with version `11.2` on target `AztecEditorTest` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
xuxiwens-MacBook-Pro:AztecEditorTest xuxiwen$

**Comment by CivelXu** [comment]
<img width="757" alt="jietu20180208-101227" src="https://user-images.githubusercontent.com/19768199/35951952-a1cd83d6-0cb8-11e8-8c6e-1ee48649d564.png">

**Comment by diegoreymendez** [comment]
I see in your logs:`Using WordPress-Aztec-iOS (0.2.0)`.

You most likely need to update the version of Aztec in your `Podfile`.  The latest version is `1.0.0-beta.18.1`.
