### ISSUE TITLE
Support for checklist

### ISSUE THREAD

**Issue by fourbears** [wordpress-mobile/AztecEditor-iOS#911]
### Expected behavior

![51519624152_ pic_hd](https://user-images.githubusercontent.com/5725823/36655162-f0383f7e-1afb-11e8-98ff-e7399e63256b.jpg)

### Actual behavior

OrderList and UnorderList are static , how to support **checklist** like 'Notes app（https://support.apple.com/en-us/HT205773）'

### Steps to reproduce the behavior

Not support yet

### Tested on iPhone 6, iPhone 7, iOS 11, Aztec develop branch

**Comment by catehstn** [comment]
Until checklists are supported in Core or WordPress.com, we won't be looking at app support. Thank you for the suggestion though!
