### ISSUE TITLE
Adding video button and Gif image button in toolbar

### ISSUE THREAD

**Issue by vinathy** [wordpress-mobile/AztecEditor-iOS#921]
How to add video and Gif button in toolbar and functionality of Gif image in source code, Any help is appreciable. Thanks in advance.

**Comment by diegoreymendez** [comment]
There's no support for GIFs in Aztec right now, this is something that would need to be implemented and tested.

Closing since this is not part of the roadmap right now, but feel free to submit a PR if you can contribute to this end.
