### ISSUE TITLE
The pasted attachment's identifier and copied attachment's identifier are same

### ISSUE THREAD

**Issue by azone** [wordpress-mobile/AztecEditor-iOS#923]
### Expected behavior

Copy one or more attachment(s) and paste, the pasted attachments' identifiers are same as the copied attachment(s)

### Actual behavior

The pasted attachment's identifier should be different from copied attachment

### Steps to reproduce the behavior

1. Insert image to the editor
2. Copy the inserted image
3. Paste in editor
4. compare their identifiers

**Comment by diegoreymendez** [comment]
Ping @SergioEstevao ^

**Comment by SergioEstevao** [comment]
Good catch! I will have a look on this.
