### ISSUE TITLE
Compilation with Xcode 9.3 fails

### ISSUE THREAD

**Issue by winklerp** [wordpress-mobile/AztecEditor-iOS#926]
### Expected behavior
Aztec should compile without any errors

### Actual behavior
Compile error:

iOS/Carthage/Checkouts/AztecEditor-iOS/Aztec/Modulemaps/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
iOS/Carthage/Checkouts/AztecEditor-iOS/Aztec/Modulemaps/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 {
       ^

### Steps to reproduce the behavior
run carthage update --platform iOS --no-use-binaries

##### Tested on [device], iOS [version], Aztec [version]
Xcode 9.3, iOS 9.3, Aztec latest development source

**Comment by chengjingfeng** [comment]
reproduce the same issue

**Comment by RaulVan** [comment]
Solved -->  [Rename libxml2 to avoid build error](https://github.com/tid-kijyun/Kanna/pull/177)

**Comment by chengjingfeng** [comment]
So I just rename libxml2 to any name I prefer it will work?

**Comment by winklerp** [comment]
i removed the libxml2 from iOS/Carthage/Checkouts/AztecEditor-iOS/Aztec/Modulemaps/libxml2/module.modulemap altogether and it seems to work

**Comment by diegoreymendez** [comment]
PR is on the way... feel free to review:

https://github.com/wordpress-mobile/AztecEditor-iOS/pull/928

**Comment by diegoreymendez** [comment]
Fixed in #928.
