### ISSUE TITLE
Can not work install by cocoapods

### ISSUE THREAD

**Issue by candyhuihui** [wordpress-mobile/AztecEditor-iOS#953]
xcode9.3.1, 26errors
![1526375394882](https://user-images.githubusercontent.com/4188731/40047806-0cef4e7e-5863-11e8-95f2-4b01a2c4a4be.jpg)

**Comment by diegoreymendez** [comment]
For Xcode 9.3 support install the latest commit No from branch `develop`.  A new release will be coming out soon.
