### ISSUE TITLE
I need latest .framework file for app store how can i get that?

### ISSUE THREAD

**Issue by GuriSarao** [wordpress-mobile/AztecEditor-iOS#974]
I am trying with beta version but build fails due to beta version getting the following error while validation.

![screen shot 2018-06-12 at 6 40 25 pm](https://user-images.githubusercontent.com/12098968/41292456-46be6ee6-6e70-11e8-9f34-45ae98d9234d.png)

**Comment by GuriSarao** [comment]
I am trying with beta version but build fails due to beta version getting the following error while validation.
![screen shot 2018-06-12 at 6 40 25 pm](https://user-images.githubusercontent.com/12098968/41292407-1cca32e6-6e70-11e8-81f5-cddec45d941f.png)

**Comment by GuriSarao** [comment]
Sorry i am new in iOS. this link helps me https://stackoverflow.com/questions/47022148/ios-how-to-generate-a-framework-file-from-a-github-project

**Comment by diegoreymendez** [comment]
Sorry we don't offer support for App development or for interacting with the App Store.
