### ISSUE TITLE
Make sure that self-closing void elements are closed the same way as Gutenberg

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/AztecEditor-iOS#987]
### Expected behavior

When opening post with self-closing elements like ```<br/> <img/> <hr/>``` I'm expecting Aztec to keep the same format on the elements and write back on the same format.

### Actual behavior

Instead we get the following ```<br> <img> <hr>```, while this is correct HTML it make changes to the HTML that then are detected has changes on the post and cause unnecessary saves/versions.

### Steps to reproduce the behavior

- Open the demo app
- Open the Gutenberg demo
- Switch to HTML
- Notice that all ```<img/> <hr/> and <br/>``` where changed to ```<br> <img> <hr>```.

**Comment by diegoreymendez** [comment]
As discussed, Aztec just outputs standard HTML, which right now isn't causing any issues with the editors we use (Calypso and Gutenberg).  Closing this as it's not currently a compatibility issue.
