### ISSUE TITLE
Gutenberg code blocks are being broken by Aztec.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#993]
### Expected behavior

Gutenberg code blocks should not be broken by Aztec.

### Actual behavior

They are not merged properly, and the comment delimiters are removed for some reason.

### Tech info

Block-level elements inside of `<pre>` should be able to merge even when they're the topmost block-level element, and they should insert a `.paragraphSeparator` between the paragraphs.

Also, here's an example code block:

```html
<!-- wp:code -->
<pre class="wp-block-code"><code>testing
test.   ing
     testing some more</code></pre>
<!-- /wp:code -->
```

### Steps to reproduce the behavior

![codeblockfail](https://user-images.githubusercontent.com/1836005/41625682-fc4aede6-73ef-11e8-878d-4bf3abdb7469.gif)

**Comment by koke** [comment]
Blocks not being merged sounds bad, but I'd be fine with the missing comments, since it doesn't affect rendering and Gutenberg can recover from that (it turns into a Classic block that you can "convert to blocks")

**Comment by koke** [comment]
@diegoreymendez did you mean to close this one with #995 ? I think github got it wrong

**Comment by diegoreymendez** [comment]
No.  Reopening.
